FROM python:3.11-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 ASDPRO_RUNTIME_DIR=/data ASD_PRO_DATA_DIR=/data ASD_MAX_UPLOAD_MB=500
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates tesseract-ocr tesseract-ocr-ita poppler-utils libgl1 libglib2.0-0 fonts-dejavu-core && rm -rf /var/lib/apt/lists/*
WORKDIR /opt/bodymind
COPY requirements_runtime.txt /opt/bodymind/requirements_runtime.txt
RUN pip install --no-cache-dir -r /opt/bodymind/requirements_runtime.txt
COPY release_apply.py /opt/bodymind/release_apply.py
COPY release_autopilot_r3.py /opt/bodymind/release_autopilot_r3.py
COPY release_autopilot_r4.py /opt/bodymind/release_autopilot_r4.py
COPY release_autopilot_r5.py /opt/bodymind/release_autopilot_r5.py
COPY release_autopilot_r6.py /opt/bodymind/release_autopilot_r6.py
COPY release_autopilot_r8.py /opt/bodymind/release_autopilot_r8.py
COPY release_autopilot_r9.py /opt/bodymind/release_autopilot_r9.py
COPY release_document_ux_r10.py /opt/bodymind/release_document_ux_r10.py
COPY release_simplify_r11.py /opt/bodymind/release_simplify_r11.py
COPY release_mobile_r12.py /opt/bodymind/release_mobile_r12.py
COPY release_unified_r13.py /opt/bodymind/release_unified_r13.py
COPY release_document_repair_r14.py /opt/bodymind/release_document_repair_r14.py
COPY release_queue_integrity_r15.py /opt/bodymind/release_queue_integrity_r15.py
COPY release_unified_flags_r16.py /opt/bodymind/release_unified_flags_r16.py
COPY release_missing_docs_r17.py /opt/bodymind/release_missing_docs_r17.py
COPY release_inbound_filefix_r18.py /opt/bodymind/release_inbound_filefix_r18.py
COPY release_pending_dedupe_r19.py /opt/bodymind/release_pending_dedupe_r19.py
COPY release_dossier_missing_r23.py /opt/bodymind/release_dossier_missing_r23.py
COPY release_ocr_rematch_r20.py /opt/bodymind/release_ocr_rematch_r20.py
COPY release_force_pdf_ocr_r21.py /opt/bodymind/release_force_pdf_ocr_r21.py
COPY release_document_flow_r25.py /opt/bodymind/release_document_flow_r25.py
COPY release_document_preview_r26.py /opt/bodymind/release_document_preview_r26.py
COPY operator_bodymind_runtime_r29.py /opt/bodymind/operator_bodymind_runtime_r29.py
COPY operator_doc_semantic_core_r52.py /opt/bodymind/operator_doc_semantic_core_r52.py
COPY operator_doc_semantic_ai_r52.py /opt/bodymind/operator_doc_semantic_ai_r52.py
COPY operator_async_upload_core_r67.py /opt/bodymind/operator_async_upload_core_r67.py
COPY release_operator_r29.py /opt/bodymind/release_operator_r29.py
COPY release_r92_operator_recover.py /opt/bodymind/release_r92_operator_recover.py
COPY release_route_cleanup_r31.py /opt/bodymind/release_route_cleanup_r31.py
COPY release_operator_r30.py /opt/bodymind/release_operator_r30.py
COPY release_mu_tutela_r34.py /opt/bodymind/release_mu_tutela_r34.py
COPY release_mu_tutela_r36.py /opt/bodymind/release_mu_tutela_r36.py
COPY release_mu_tutela_r37.py /opt/bodymind/release_mu_tutela_r37.py
COPY release_document_coherence_r41.py /opt/bodymind/release_document_coherence_r41.py
COPY release_document_coherence_r42.py /opt/bodymind/release_document_coherence_r42.py
COPY release_operator_dedupe_rollback_r43.py /opt/bodymind/release_operator_dedupe_rollback_r43.py
COPY release_document_conflict_audit_r44.py /opt/bodymind/release_document_conflict_audit_r44.py
COPY release_cloud_native_r47.py /opt/bodymind/release_cloud_native_r47.py
COPY release_secretary_capability_audit_r48.py /opt/bodymind/release_secretary_capability_audit_r48.py
COPY release_operator_batch_r52.py /opt/bodymind/release_operator_batch_r52.py
COPY release_operator_upload_semantic_r52.py /opt/bodymind/release_operator_upload_semantic_r52.py
COPY release_operator_web_audio_r52.py /opt/bodymind/release_operator_web_audio_r52.py
COPY release_operator_autonomy_r55.py /opt/bodymind/release_operator_autonomy_r55.py
COPY release_operator_fast_dedupe_r56.py /opt/bodymind/release_operator_fast_dedupe_r56.py
COPY release_operator_dedupe_smoke_r56.py /opt/bodymind/release_operator_dedupe_smoke_r56.py
COPY release_operator_avatar_r57.py /opt/bodymind/release_operator_avatar_r57.py
COPY release_operator_voice_state_r59.py /opt/bodymind/release_operator_voice_state_r59.py
COPY release_operator_targeted_missing_r60.py /opt/bodymind/release_operator_targeted_missing_r60.py
COPY release_operator_response_scope_r61.py /opt/bodymind/release_operator_response_scope_r61.py
COPY release_operator_query_polarity_r62.py /opt/bodymind/release_operator_query_polarity_r62.py
COPY release_operator_cloud_first_r63.py /opt/bodymind/release_operator_cloud_first_r63.py
COPY release_operator_persistent_upload_r64.py /opt/bodymind/release_operator_persistent_upload_r64.py
COPY enrollment_ingest_core_r65.py /opt/bodymind/enrollment_ingest_core_r65.py
COPY release_handwriting_enrollment_r65.py /opt/bodymind/release_handwriting_enrollment_r65.py
COPY release_operator_async_upload_r67.py /opt/bodymind/release_operator_async_upload_r67.py
COPY verified_mu_sync_core_r68.py /opt/bodymind/verified_mu_sync_core_r68.py
COPY release_verified_mu_profile_sync_r68.py /opt/bodymind/release_verified_mu_profile_sync_r68.py
COPY runtime_annunziato_readonly_r71.py /opt/bodymind/runtime_annunziato_readonly_r71.py
COPY release_global_reconcile_r69.py /opt/bodymind/release_global_reconcile_r69.py
COPY release_complete_mu_cache_r70.py /opt/bodymind/release_complete_mu_cache_r70.py
COPY release_guardian_refresh_r71.py /opt/bodymind/release_guardian_refresh_r71.py
COPY release_shared_document_core_r72.py /opt/bodymind/release_shared_document_core_r72.py
COPY release_document_consistency_r74.py /opt/bodymind/release_document_consistency_r74.py
COPY release_operator_document_core_r78.py /opt/bodymind/release_operator_document_core_r78.py
COPY release_mu_canonical_r79.py /opt/bodymind/release_mu_canonical_r79.py
COPY release_stabilization_audit_r80.py /opt/bodymind/release_stabilization_audit_r80.py
COPY release_mobile_delete_r85.py /opt/bodymind/release_mobile_delete_r85.py
COPY release_mobile_athlete_delete_r87.py /opt/bodymind/release_mobile_athlete_delete_r87.py
COPY release_operator_ios_keyboard_r90.py /opt/bodymind/release_operator_ios_keyboard_r90.py
COPY release_unassigned_mu_audit_r91.py /opt/bodymind/release_unassigned_mu_audit_r91.py
COPY release_new_athlete_profile_audit_r93.py /opt/bodymind/release_new_athlete_profile_audit_r93.py
COPY release_profile_schema_audit_r94.py /opt/bodymind/release_profile_schema_audit_r94.py
COPY release_mu_residenza_r95.py /opt/bodymind/release_mu_residenza_r95.py
COPY release_medical_criticality_audit_r96.py /opt/bodymind/release_medical_criticality_audit_r96.py
COPY release_medical_save_audit_r97.py /opt/bodymind/release_medical_save_audit_r97.py
COPY release_medical_save_compact_r98.py /opt/bodymind/release_medical_save_compact_r98.py
COPY release_active_route_audit_r99.py /opt/bodymind/release_active_route_audit_r99.py
COPY release_medical_profile_convergence_r100.py /opt/bodymind/release_medical_profile_convergence_r100.py
COPY release_criticality_profile_r101.py /opt/bodymind/release_criticality_profile_r101.py
COPY release_desktop_profile_audit_r104.py /opt/bodymind/release_desktop_profile_audit_r104.py
COPY release_desktop_update_source_r105.py /opt/bodymind/release_desktop_update_source_r105.py
COPY release_desktop_save_convergence_r106.py /opt/bodymind/release_desktop_save_convergence_r106.py
COPY release_operator_attachment_create_r107.py /opt/bodymind/release_operator_attachment_create_r107.py
COPY release_mu_metadata_convergence_r108.py /opt/bodymind/release_mu_metadata_convergence_r108.py
COPY release_mu_autoenroll_r92.py /opt/bodymind/release_mu_autoenroll_r92.py
COPY release_ui_regression_smoke_r84.py /opt/bodymind/release_ui_regression_smoke_r84.py
COPY release_stabilization_repair_r81.py /opt/bodymind/release_stabilization_repair_r81.py
COPY release_guardian_convergence_r82.py /opt/bodymind/release_guardian_convergence_r82.py
COPY release_handwriting_enrollment_smoke_r65.py /opt/bodymind/release_handwriting_enrollment_smoke_r65.py
COPY release_operator_upload_smoke_r64.py /opt/bodymind/release_operator_upload_smoke_r64.py
COPY release_operator_cloud_first_smoke_r63.py /opt/bodymind/release_operator_cloud_first_smoke_r63.py
COPY release_operator_polarity_smoke_r62.py /opt/bodymind/release_operator_polarity_smoke_r62.py
COPY release_operator_scope_smoke_r61.py /opt/bodymind/release_operator_scope_smoke_r61.py
COPY release_operator_targeted_smoke_r60.py /opt/bodymind/release_operator_targeted_smoke_r60.py
COPY release_operator_intent_smoke_r57.py /opt/bodymind/release_operator_intent_smoke_r57.py
COPY release_operator_pending_reconcile_r55.py /opt/bodymind/release_operator_pending_reconcile_r55.py
COPY release_operator_pending_audit_r55e.py /opt/bodymind/release_operator_pending_audit_r55e.py
COPY release_operator_dinicola_r55f.py /opt/bodymind/release_operator_dinicola_r55f.py
COPY release_operator_read_smoke_r53.py /opt/bodymind/release_operator_read_smoke_r53.py
COPY release_operator_experience_r38.py /opt/bodymind/release_operator_experience_r38.py
COPY release_operator_qa_r32.py /opt/bodymind/release_operator_qa_r32.py
COPY release_operator_logic_qa_r34.py /opt/bodymind/release_operator_logic_qa_r34.py
COPY release_operator_logic_qa_r37.py /opt/bodymind/release_operator_logic_qa_r37.py
COPY release_operator_mobile_r33.py /opt/bodymind/release_operator_mobile_r33.py
COPY release_cleanup_r2.py /opt/bodymind/release_cleanup_r2.py
COPY runtime_timeline_inspect_r35.py /opt/bodymind/runtime_timeline_inspect_r35.py
COPY release_route_guard_r39.py /opt/bodymind/release_route_guard_r39.py
COPY build_preflight_r39.py /opt/bodymind/build_preflight_r39.py
COPY runtime_launcher.py /opt/bodymind/runtime_launcher.py
RUN python /opt/bodymind/build_preflight_r39.py
RUN mkdir -p /opt/bodymind-migration && cp /opt/bodymind/runtime_launcher.py /opt/bodymind-migration/migration_upload.py
EXPOSE 8080
CMD ["python","/opt/bodymind-migration/migration_upload.py"]
